---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ SQS queue
    ## Description
    {{ .Header }}
    This module provides the following capabilities:
    * 🚀 **SQS queue**: SQS queue with the specified name.
    * 🚀 **Dead-letter queue**: Dead-letter queue to store messages that can't be delivered.
    It also supports the creation of [FIFO queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html) and [Standard queues](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues.html).
    For more information about these resources, please visit the [AWS documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html), and also the terraform specific documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sqs_queue).

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../../examples/sqs/sqs-queue/basic/main.tf" }}
    ```

    Simple example of a basic implementation.
    ```hcl
    {{ include "../../../examples/sqs/sqs-queue/basic/fixtures/fixtures.tfvars" }}
    ```

    A queue with a dead-letter queue.
    ```hcl
    {{ include "../../../examples/sqs/sqs-queue/basic/fixtures/fixtures-with-dlq-simple.tfvars" }}
    ```

    A FIFO queue.
    ```hcl
    {{ include "../../../examples/sqs/sqs-queue/basic/fixtures/fixtures-with-fifo.tfvars" }}
    ```

    A queue with policies attached
    ```hcl
    {{ include "../../../examples/sqs/sqs-queue/basic/fixtures/fixtures-with-policies.tfvars" }}
    ```


    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
