---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ Event bridge permissions
    ## Description

    {{ .Header }}

    This is a custom module that bring out-of-the-fox permissions for common use-cases for eventbridge. It's just an abstraction that takes care of creating IAM roles, and a set of permissions for eventbridge.
    * 🚀 **IAM role**: IAM role that will be created and attached to the eventbridge rule.
    * 🚀 **IAM policy**: IAM policy that will be created and attached to the IAM role.

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../../examples/eventbridge/eventbridge-permissions/basic/main.tf" }}
    ```

    Simple example of a basic implementation.
    ```hcl
    {{ include "../../../examples/eventbridge/eventbridge-permissions/basic/fixtures/fixtures.tfvars" }}
    ```

    Example where lambda permissions are set, in order to invoke an AWS Lambda function.
    ```hcl
    {{ include "../../../examples/eventbridge/eventbridge-permissions/basic/fixtures/fixtures-permissions-lambda.tfvars" }}
    ```

    Example where custom IAM policy documents are passed.
    ```hcl
    {{ include "../../../examples/eventbridge/eventbridge-permissions/basic/fixtures/fixtures-custom-policies.tfvars" }}
    ```

    Example where custom policy ARNs are passed
    ```hcl
    {{ include "../../../examples/eventbridge/eventbridge-permissions/basic/fixtures/fixtures-attach-policies-arns.tfvars" }}
    ```

    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
