---
formatter: markdown table

header-from: main.tf
content: |-
    # ☁️ SNS topic
    ## Description
    {{ .Header }}
    This module creates an event bridge rule, with the following capabilities:
    * 🚀 **SNS topic**: SNS topic with the specified name.
    * 🚀 **SNS topic policy**: SNS topic policy to control access to the topic.
    For more information about these resources, please visit the [AWS documentation](https://docs.aws.amazon.com/sns/latest/dg/welcome.html), and also the terraform specific documentation [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sns_topic).

    ---
    ## Example
    Examples of this module's usage are available in the [examples](./examples) folder.

    ```hcl
    {{ include "../../../examples/sns/sns-topic/basic/main.tf" }}
    ```

    Simple example of a basic implementation.
    ```hcl
    {{ include "../../../examples/sns/sns-topic/basic/fixtures/fixtures.tfvars" }}
    ```

    An example that shows how to create a topic with a custom policy.
    ```hcl
    {{ include "../../../examples/sns/sns-topic/basic/fixtures/fixtures-with-custom-sns-topic-policy.tfvars" }}
    ```

    It's also possible to pass a list of AWS services that can publish to the topic.
    ```hcl
    {{ include "../../../examples/sns/sns-topic/basic/fixtures/fixtures-with-publisher-permissions-aws-services.tfvars" }}
    ```

    For module composition, It's recommended to take a look at the module's `outputs` to understand what's available:
    ```hcl
    {{ include "outputs.tf" }}
    ```
    ---

    ## Module's documentation
    (This documentation is auto-generated using [terraform-docs](https://terraform-docs.io))
    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Requirements }}

    {{ .Inputs }}

    {{ .Outputs }}

output:
    file: README.md
    mode: inject
    template: |-
        <!-- BEGIN_TF_DOCS -->
        {{ .Content }}
        <!-- END_TF_DOCS -->
settings:
    anchor: true
    color: true
